# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e7f6c30abfa08778f323b32cade79dcfb31b674886d7cc8da3cbf9fd2628b12f1a3e90bc561f61b75624475e6f29b5ed631991c63cde82a7c433a1a123b4685

test:
  secret_key_base: dc65af9bc29a1acd77e18c60eb8fd7ccd2e3291fb9bfe1b670eb5ec371603be0db913f9d735dfbe2f3fb241bfb24ac5df2eb6125ad3d61a20a1380c5250cc0c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
